select * from customer

-- What is the total revenue generated by male vs female customer 

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- which customers used a discount but still spend more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)
                                                       from customer)
select * from customer 

--Which are the top 5 products with the highest average review rating

select item_purchased,round(avg(review_rating::numeric),4) as "Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5

select * from customer 
-- Compare the avg purchase amounts between standard and express shipping 
select shipping_type, round(avg(purchase_amount),2)
from customer 
where shipping_type in('Standard','Express')
group by shipping_type

-- do subscribed customers spend more ? compare average spend and total revenue between 
--  subscribers and non-subscribers
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue, avg_spend desc

select * from customer
-- which 5 products have the highest percentage of purchases with  discount applied
select item_purchased, 
round(100 * SUM(case when discount_applied = 'Yes' THEN 1 else 0 end)/count(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5
-- segment customer into New,Returning,and Loyal based on their totalnumber of previuos purchases, and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case when previous_purchases = 1 Then 'New'
     when previous_purchases Between 2 and 19 THEN 'Returning'
	 ELSE 'Loyal'
	 End as customer_segment
from customer)
Select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment
 
--What are the top 3 segment purchased products within each category
with item_counts as (
select category,item_purchased,COUNT(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id)DESC) as item_rank
 from customer
 group by category,item_purchased)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3
--What are the top 3 most purchased products within each category
with item_counts as(
select category, item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3
--Are customer who are repeat buyers(more than 5 previouses) also likely to subscribe
Select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

select * from customer

-- What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc










